### ISSUE TITLE
Can the flow-registration applied to the 3D volume?

### ISSUE THREAD

**Issue by cindy12-gao** [phflot/flow_registration#11]

**Comment by phflot** [comment]
Generally, it should be possible. for 3D volumes, I would use a small batch size with an adaptive reference and a large smoothness weight such that changing structures are not warped too much - it definitely depends on how your data looks like.

**Comment by phflot** [comment]
Could you give me more information on what exact data you want to compensate, maybe even a small example?

**Comment by phflot** [comment]
Native 3D support will be added soon, is this still relevant and do you have a use case?
