### ISSUE TITLE
set_path

### ISSUE THREAD

**Issue by milesOIST** [phflot/flow_registration#14]
Running on the cluster, I got an error from this line:
`currentdir = fileparts( mfilename('fullpath') );`
so I changed it to:
`currentdir = pwd;`
which worked.

**Comment by phflot** [comment]
Could you send me the error message that it produced?

**Comment by milesOIST** [comment]
It couldn't find the files. Strangely, this code works on my desktop (2021b). Maybe has to do with the Matlab version? The cluster is using R2020b. 

Building with 'g++'.
Error using mex
Unable to read '/hpcshare/apps/unit/User/flow_registration/core/level_solver.mexa64'. Change file permission to readable.

Error in make (line 15)
    mex(varargin{:}, 'level_solver.cpp');

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in set_path (line 11)
run(fullfile(currentdir, 'core', 'make.m'));

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in HDF5_FlowReg_deigo (line 5)
run('/apps/unit/User/flow_registration/set_path.m');

**Comment by phflot** [comment]
Could you try running this from within a different folder and see if this is caused by limited writing permissions? The last error looks like it can't recompile the code. If you managed to compile it once, you could also try to skip building the mex files and only add the paths.
