### ISSUE TITLE
Question about HDF_file_writer

### ISSUE THREAD

**Issue by milesOIST** [phflot/flow_registration#16]
Could I ask how to set the dimensions of the output for a HDF5 file? I would like to have channels as the final dimension, i.e. [X, Y, time, ch]. I see that 'dimension_ordering' is a named argument, but that it must satisfy length(x)==3. How can I specify where the 4th dimension (channel) comes?

**Comment by phflot** [comment]
Dear Miles,
sorry for the slow replies, if you look into the hdf5 files, they are organized as one 3D dataset per channel. Only the file readers return 4D videos in the end. 
Would storage of 4D datasets in hdf5 (with custom ordering) be something you need or do you need [X, Y, time, ch] ordering in MATLAB (basically an option for the video readers)?
Best wishes,
Philipp

**Comment by phflot** [comment]
ah or you can store it as one hdf5 file per channel with the "MULTIFILE_HDF" option.
