### ISSUE TITLE
get_video_file_reader with BEGONIA compensated files

### ISSUE THREAD

**Issue by milesOIST** [phflot/flow_registration#5]
Error when running on files compensated using 'BEGONIA' option. 
vid = get_video_file_reader('compensated.h5');
Error using HDF_file_reader (line 63)
no 3D dataset found in file compensated.h5

Error in get_video_file_reader (line 39)
            video_file_reader = HDF_file_reader(input_file, ...

**Comment by milesOIST** [comment]
Just wondering if there has been any progress on this?

**Comment by phflot** [comment]
Support for those files is implemented now. Please let me know in case there is any unexpected behaviour,
best wishes,
Philipp
