### ISSUE TITLE
how to apply the same transform parameters according to one channel to different channels? 

### ISSUE THREAD

**Issue by cindy12-gao** [phflot/flow_registration#7]
hi, there is a different application .
I want register Image series from consecutive hybridizations. there is a refenrence channel-dapi, so can i apply the dapi channel transform parameters to other channels, which may don`t have feature structure?

**Comment by phflot** [comment]
Hello, I think what you are trying to do can be achieved with different approaches.
If you reduce the parameter `weight` for the channel without structure (e.d. `weight = [1.8, 0.2]`, it will be downweighted when estimating the displacements but will be registered. While this is computationally slightly more expensive than single channel, it is advantageous when there is residual, structural information left for example due to indicator bleed. 

Another possibility is, when you set `save_w` to true, the estimated displacements will be stored in a hdf file in your output folder. Here is an example piece of code that would allow you to register any recording with the reference displacements:
```Matlab
input_file = 'example.h5';
structure_channel = get_video_file_reader(input_file, 50, 1, ...
    'dataset_names', 'ch1');
functional_channel = get_video_file_reader(input_file, 50, 1, ...
    'dataset_names', 'ch2');
output_folder = 'results';


options = OF_options(...
    'input_file', video_reader, ...
    'output_path', output_folder, ... 
    'output_format', 'HDF5', ...
    'alpha', 4, ...
    'save_w', true, ...
    'quality_setting', 'balanced', ... 
    'reference_frames', 1:20 ...
    );

compensate_recording(options);

w = get_video_file_reader(fullfile(output_folder, 'w.hdf'), 50, 1);
output_file_writer = get_video_file_writer(fullfile(output_folder, 'functional_channel.hdf'), 'HDF5');

while (w.has_batch())
    displacements = w.read_batch();
    func_frames = functional_channel.read_batch();
    output_file_writer.write_frames(compensate_sequence_uv(func_frames, mean(func_frames, 4), displacements));
end

% sanity test, showing the average of the compensated channel:
test = get_video_file_reader(fullfile(output_folder, 'functional_channel.hdf'));
imshow(mat2gray(mean(test.read_frames(1:test.frame_count), 4)));
```

The script works with an hdf5 file with two channels, where we assume that 'ch1' is the structural and 'ch2' is the functional channel. The compensated functional channel is stored into the file 'functional_channel.hdf'.
Please let me know whether I can close the issue and feel free to post the functionality additionally as a feature request.
Best wishes,
Philipp

**Comment by cindy12-gao** [comment]
thank for your reply, for the first way,the position of weight parameter`s definition is the area showed like follow?
![question](https://user-images.githubusercontent.com/72720700/175054646-3f45e6ed-1016-46af-b7a4-cbcd07eecc0c.png)

**Comment by phflot** [comment]
yes exactly, when you set it to 0 for one of the channels, the channel won't be considered during motion compensation, but it will be compensated.
Would it be helpful if this functionality would be integrated differently into the plugin?

**Comment by cindy12-gao** [comment]
as for the method 2, I`ve tried it, but there something wrong. Now my raw data is 6400*6400*2(channel)*2(timepoint),
and I saved it as tiff stack
![data save](https://user-images.githubusercontent.com/72720700/175198270-2610015d-e688-4b67-a48d-4008e2a26c35.PNG)
![data raw](https://user-images.githubusercontent.com/72720700/175198361-daa4a158-ad84-4ee6-bd1c-e9e32086a7fc.PNG)
script as follow:
clear all;
clc
%run('../set_path.m');

output_folder = 'jupiter_demo';
if ~isfolder(output_folder)
    mkdir(output_folder)
end
input_file = fullfile(output_folder, 'timelapse.tif');
% if (~exist(input_file, 'file'))
%     websave(input_file, ...
%         'https://cloud.hiz-saarland.de/s/JpHyczRSMDbLwzP/download');
% end

%% preparing file writers and readers:
% creating the file reader (could also be MDF, maybe use:
% get_video_file_reader('input.mdf', 50, 5); to read frame batches of size 50
% with binning over 5 frames):

buffer_size = 50;
% In this example, we simulate a multichannel file by adding the same input
% file multiple times:
vid = get_video_file_reader({input_file, input_file}, buffer_size);

% creating the file writers, check get_video_file_writer for supported
% parameters. It can also take a string or cell (must fit the number of 
% channels!)as parameter to name the dataset, can contain * to indicate the
% position for the channel number:
% hdf5_writer_single = get_video_file_writer(...
%     fullfile(output_folder, 'jup_single.hdf5'), 'HDF5', 'dataset_names', 'ch*');
hdf5_writer_mult = get_video_file_writer(...
    fullfile(output_folder, 'jup_mult.hdf5'), 'MULTIFILE_HDF5', 'dataset_names', '/vid');

%% converting the tiff file to two different hdf formats:
while(vid.has_batch)
    tmp = vid.read_batch;
    hdf5_writer_mult.write_frames(tmp);
  %  hdf5_writer_single.write_frames(tmp);
end
%%
input_file_ch1 = fullfile(output_folder, 'jup_mult_ch1.HDF5');
input_file_ch2 = fullfile(output_folder, 'jup_mult_ch2.HDF5');

structure_channel = get_video_file_reader(input_file_ch1, 50, 1, ...
    'dataset_names', 'ch1');
functional_channel = get_video_file_reader(input_file_ch2, 50, 1, ...
    'dataset_names', 'ch2');
there is error
![wrong](https://user-images.githubusercontent.com/72720700/175198705-21f9d68a-73de-44f6-9ec1-5934a6be6aa4.PNG)
could you please help me to find the reason ?

**Comment by phflot** [comment]
Hello,
I would recommend to use the jupiter minimal demo. For example,
```Matlab
vid = get_video_file_reader({input_file, input_file}, buffer_size);
```
creates a video File reader object, which contains two times the same channels from inputfile (as a demo!). 
If your multichannel tifs are stored with interleaving, you should call
```Matlab
vid = get_video_file_reader(input_file, 'deinterleave', true);
```
Your specific error seems comes from the fact, that you are creating 
```Matlab
hdf5_writer_mult = get_video_file_writer(...
fullfile(output_folder, 'jup_mult.hdf5'), 'MULTIFILE_HDF5', 'dataset_names', '/vid');
```
which will generate one file for each channel with channel name vid and then you try to open the files with ``dataset_names`` ch1 and ch2 which should be ``vid``.
Would it be possible for you to supply me with a minimal tiff file that is formatted like the data you are working with (can be an empty recording if you can't share data) with which I can check whether the video readers are compatible and debug, also for the FIJI plugin?

**Comment by cindy12-gao** [comment]
http://gofile.me/6Uroj/G2b63pKYZ
you can download the data from this link. thank you

**Comment by phflot** [comment]
Thank you for the upload, so each of the files contains two frames at different time and _HyperStack-test-dapi_ is the reference?
If that is correct, the following code will compensate the two channels into two tiff files in folder ```results_ref``` and visualizes the results (see attached figure). Only the dapi channel is used for correction - best try to run it with the files you have sent me and check the results in ImageJ, you will see the joint structures in ch2 are aligned well:
```Matlab
video_reader = get_video_file_reader({'HyperStack-test-dapi.tif', 'HyperStack-test-2.tif'});
output_folder = 'results_ref';

options = OF_options(...
    'input_file', video_reader, ...
    'output_path', output_folder, ... 
    'weight', [1, 0], ...
    'output_format', 'MULTIFILE_TIFF', ...
    'sigma', [3, 3, 0.01], ...
    'alpha', 4, ...
    'quality_setting', 'balanced', ... 
    'reference_frames', 1, ...
    'output_typename', '' ...
    );

compensate_recording(options);

video_reader = get_video_file_reader({fullfile(output_folder, 'compensated_ch1.TIFF'), ...
    fullfile(output_folder, 'compensated_ch2.TIFF')});
compensated = video_reader.read_frames(1:video_reader.frame_count);
figure
subplot(1, 2, 1);
imshowpair(mat2gray(compensated(:, :, 1, 1)), mat2gray(compensated(:, :, 1, 2)));
subplot(1, 2, 2);
imshowpair(compensated(:, :, 2, 1), compensated(:, :, 2, 2));
```
Please let me know if this solved your problem,
Best wishes,
Philipp


Output from the script:
![results](https://user-images.githubusercontent.com/12631613/175812987-b2593eeb-e998-4091-ab03-568c45d49694.PNG)

**Comment by phflot** [comment]
I have updated alpha in the previous comment to 1 which seems to be a better choice for your. There are some misregistrations in the lower left part, you could try to define a weight mask around the rectangular region and set the weights there to 0 which should improve registration.
Setting the quality setting to "quality" will further improve the results.
